from __future__ import annotations

import re
from collections.abc import Iterable
from datetime import UTC, datetime
from typing import Any

from datamixxer import __version__

DEFAULT_ARTIFACT_VERSION = "v1"


def artifact_version(config: dict[str, Any]) -> str:
    value = config.get("version") or config.get("artifact_version") or DEFAULT_ARTIFACT_VERSION
    version = str(value).strip()
    if not version:
        version = DEFAULT_ARTIFACT_VERSION
    if re.fullmatch(r"\d+(?:\.\d+)*", version):
        version = f"v{version}"
    return slugify(version)


def slugify(value: Any) -> str:
    slug = str(value).strip().lower()
    slug = re.sub(r"[^a-z0-9._-]+", "-", slug)
    slug = re.sub(r"-{2,}", "-", slug)
    slug = re.sub(r"\.{2,}", ".", slug)
    slug = slug.strip(".-")
    if not slug:
        raise ValueError("artifact name cannot be empty after slug normalization")
    return slug


def versioned_slug(value: Any, version: str) -> str:
    slug = slugify(value)
    suffix = slugify(version)
    return slug if slug.endswith(f"-{suffix}") else f"{slug}-{suffix}"


def standard_repo_id(
    hub: dict[str, Any], *, fallback_name: str, version: str, required: bool = True
) -> str | None:
    repo_id = hub.get("repo_id")
    if repo_id:
        return str(repo_id)
    owner = hub.get("owner")
    if owner:
        return f"{owner}/{versioned_slug(fallback_name, version)}"
    if required:
        raise KeyError("hub.repo_id or hub.owner is required for publishing")
    return None


def now_iso() -> str:
    return datetime.now(UTC).isoformat()


def markdown_table(headers: list[str], rows: Iterable[Iterable[Any]]) -> str:
    rendered = ["| " + " | ".join(headers) + " |"]
    rendered.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        rendered.append("| " + " | ".join(_cell(value) for value in row) + " |")
    return "\n".join(rendered)


def dataset_card(
    *,
    config: dict[str, Any],
    manifest: dict[str, Any],
    repo_id: str | None,
) -> str:
    version = str(manifest["artifact_version"])
    source_rows = [
        [
            item["name"],
            item["dataset_id"],
            item.get("config") or "",
            item["split"],
            item["count"],
            item["train_count"],
            item["test_count"],
        ]
        for item in manifest["sources"]
    ]
    split_rows = [[name, counts["rows"]] for name, counts in manifest["splits"].items()]
    bucket_rows = [
        [bucket, split, count]
        for split, buckets in manifest["buckets_by_split"].items()
        for bucket, count in sorted(buckets.items())
    ]
    return "\n".join(
        [
            "---",
            "tags:",
            "- datamixxer",
            "- dataset-mix",
            "- versioned-artifact",
            "pretty_name: " + _yaml_scalar(f"{config.get('name', config['id'])} {version}"),
            "---",
            "",
            f"# {config.get('name', config['id'])} {version}",
            "",
            "## Overview",
            "",
            "This dataset mix was produced by `datamixxer build`. It contains",
            "deterministic subsamples from the configured Hugging Face dataset splits.",
            "When both train and test files are present, each source bucket was split",
            "independently so both output splits preserve the configured blend.",
            "",
            "## Versioning and Naming",
            "",
            markdown_table(
                ["Field", "Value"],
                [
                    ["Artifact type", manifest["artifact_type"]],
                    ["Artifact id", manifest["artifact_id"]],
                    ["Artifact version", version],
                    ["Hub repo", repo_id or "not configured"],
                    ["Generated by", f"datamixxer {__version__}"],
                    ["Generated at", manifest["created_at"]],
                ],
            ),
            "",
            "## Output Splits",
            "",
            markdown_table(["Split", "Rows"], split_rows),
            "",
            "## Source Plan",
            "",
            markdown_table(
                ["Bucket", "Dataset", "Config", "Source split", "Rows", "Train", "Test"],
                source_rows,
            ),
            "",
            "## Composition",
            "",
            markdown_table(["Bucket", "Output split", "Rows"], bucket_rows),
            "",
            "## Schema",
            "",
            "Rows preserve the original source columns and add `bucket`,",
            "`source_dataset`, `source_config`, and `source_split` metadata columns.",
            "Per-source `metadata` values from the config are also copied into rows.",
            "",
            "## Reproduction",
            "",
            "```bash",
            f"datamixxer build {manifest.get('config_path') or config['id'] + '.yaml'}",
            "```",
            "",
            "## Limitations",
            "",
            "This dataset inherits quality, license, safety, and representativeness",
            "properties from every configured upstream dataset.",
            "",
        ]
    )


def _cell(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _yaml_scalar(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
